import type { Locator, Page } from '@playwright/test';

import { expect, resetStub, test } from './fixtures';

/**
 * The library upload flow, and PART-scoped access cards.
 *
 * The upload tests drive a real file through a real cross-origin PUT to the
 * storage stand-in — preflight included — because that is the part of the flow
 * the product actually has. Mocking the PUT would leave the one step most
 * likely to break untested.
 */

const STUB_API = `http://127.0.0.1:${process.env.STUB_API_PORT ?? 4599}`;

test.beforeEach(async ({ page }) => {
  await resetStub(page);
});

/** A small, genuinely valid PDF, so nothing depends on the bytes. */
const PDF = {
  name: 'revision-paper.pdf',
  mimeType: 'application/pdf',
  buffer: Buffer.from('%PDF-1.4\n1 0 obj\n<<>>\nendobj\ntrailer\n<<>>\n%%EOF\n'),
};

/**
 * The English title, not the Arabic one.
 *
 * `getByLabel('Title')` matches on a substring, so it finds both `Title
 * (required)` and `Title (Arabic)` and Playwright refuses the ambiguity. The
 * accessible name carries the screen-reader-only "(required)" the `Field`
 * appends, which is what makes the two distinguishable.
 */
function fillTitle(dialog: Locator, value: string) {
  return dialog.getByRole('textbox', { name: 'Title (required)' }).fill(value);
}

async function openAddDocument(page: Page) {
  await page.goto('/library/mat-1');
  await page.getByRole('button', { name: 'Add document' }).first().click();
  return page.getByRole('dialog');
}

// ---------------------------------------------------------------------------
// Library upload
// ---------------------------------------------------------------------------

test.describe('library upload', () => {
  test('uploads a chosen file and reports it as uploaded', async ({ page, signIn }) => {
    await signIn('admin');
    const dialog = await openAddDocument(page);

    await dialog.locator('input[type="file"]').setInputFiles(PDF);

    await expect(dialog.getByText('Uploaded')).toBeVisible();
    await expect(dialog.getByText(PDF.name)).toBeVisible();
  });

  test('offers no place to type a storage key', async ({ page, signIn }) => {
    // The manual key was never something an administrator could get right:
    // the key is generated by the server and only appears in a response.
    await signIn('admin');
    const dialog = await openAddDocument(page);

    await expect(dialog.getByLabel(/object key/i)).toHaveCount(0);
    await expect(dialog.getByPlaceholder(/library\//)).toHaveCount(0);
  });

  test('refuses to save a new document before a file is uploaded', async ({ page, signIn }) => {
    await signIn('admin');
    const dialog = await openAddDocument(page);

    await fillTitle(dialog, 'Paper 3');
    await dialog.getByLabel('Price').fill('75');

    // No file yet, so the part would point at nothing.
    await expect(dialog.getByRole('button', { name: 'Add document' })).toBeDisabled();
  });

  test('creates the document with the key the server issued', async ({ page, signIn }) => {
    await signIn('admin');
    const dialog = await openAddDocument(page);

    await fillTitle(dialog, 'Paper 3');
    await dialog.getByLabel('Price').fill('75');
    await dialog.locator('input[type="file"]').setInputFiles(PDF);
    await expect(dialog.getByText('Uploaded')).toBeVisible();

    await Promise.all([
      page.waitForResponse(
        (r) =>
          r.url().includes('/api/proxy/admin/library/materials/') &&
          r.request().method() === 'POST',
      ),
      dialog.getByRole('button', { name: 'Add document' }).click(),
    ]);

    // Asserted on the request, not on the screen: the claim is that the
    // dashboard sent the server's key, and a rendered string cannot show that.
    const sent = await (
      await page.request.get(`${STUB_API}/api/v1/__test__/last-library-part`)
    ).json();

    expect(sent.data.objectKey).toBe('library/stub-object.pdf');
    expect(sent.data.title).toBe('Paper 3');
    expect(sent.data.price).toBe(75);
  });

  test('reports a failed upload and does not pretend it worked', async ({ page, signIn }) => {
    await signIn('admin');
    await page.request.get(`${STUB_API}/api/v1/__test__/fail-upload`);

    const dialog = await openAddDocument(page);
    await dialog.locator('input[type="file"]').setInputFiles(PDF);

    await expect(dialog.getByRole('alert')).toContainText(/storage refused|could not reach/i);
    await expect(dialog.getByText('Uploaded')).toHaveCount(0);
  });

  test('rejects a file type the server would refuse, without a round trip', async ({
    page,
    signIn,
  }) => {
    await signIn('admin');
    const dialog = await openAddDocument(page);

    await dialog.locator('input[type="file"]').setInputFiles({
      name: 'notes.txt',
      mimeType: 'text/plain',
      buffer: Buffer.from('hello'),
    });

    await expect(dialog.getByRole('alert')).toContainText(/file type is not accepted/i);
  });

  test('never exposes a permanent or public storage URL', async ({ page, signIn }) => {
    // The bucket is private. The upload URL is a short-lived write-only
    // signature, and it must not survive into anything the page renders.
    await signIn('admin');
    const dialog = await openAddDocument(page);

    await dialog.locator('input[type="file"]').setInputFiles(PDF);
    await expect(dialog.getByText('Uploaded')).toBeVisible();

    const text = (await dialog.textContent()) ?? '';
    expect(text).not.toContain('__storage__');
    expect(text).not.toContain('http://');
    expect(text).not.toContain('https://');
    expect(text).not.toContain('library/stub-object');

    await expect(dialog.getByRole('link')).toHaveCount(0);
  });

  test('the presign endpoint is refused to a teacher', async ({ page, signIn }) => {
    // @AdminOnly() on the real controller — there is no teacher-scoped
    // library route anywhere.
    await signIn('teacher');

    const response = await page.request.post('/api/proxy/storage/uploads/library-document', {
      headers: { 'x-dashboard-request': '1', origin: new URL(page.url()).origin },
      data: { filename: 'a.pdf', contentType: 'application/pdf', sizeBytes: 10 },
    });

    expect(response.status(), await response.text()).toBe(403);
  });
});

// ---------------------------------------------------------------------------
// PART-targeted access cards
// ---------------------------------------------------------------------------

async function openGenerate(page: Page) {
  await page.goto('/codes');
  await page
    .getByRole('button', { name: /generate codes/i })
    .first()
    .click();
  return page.getByRole('dialog');
}

test.describe('PART access cards', () => {
  test('offers PART as a target alongside the existing three', async ({ page, signIn }) => {
    await signIn('admin');
    const dialog = await openGenerate(page);

    const target = dialog.getByLabel('What do these cards unlock?');
    await expect(target.locator('option')).toHaveText([
      'A whole course',
      'One part of a course',
      'One section of a course',
      'Everything by one teacher',
    ]);
  });

  test('loads the parts of the chosen course', async ({ page, signIn }) => {
    await signIn('admin');
    const dialog = await openGenerate(page);

    await dialog.getByLabel('What do these cards unlock?').selectOption('PART');
    await dialog.getByLabel('Course').selectOption('course-1');

    // Part 1 has a section; Part 2 has none, so a card for it would unlock
    // nothing and the server refuses it. It is not offered.
    await expect(dialog.getByLabel('Part').locator('option')).toContainText([
      'Part 1 - Before mid',
    ]);
    await expect(dialog.getByLabel('Part')).not.toContainText('Part 2 - After mid');
  });

  test('will not generate until a part is chosen', async ({ page, signIn }) => {
    await signIn('admin');
    const dialog = await openGenerate(page);

    await dialog.getByLabel('What do these cards unlock?').selectOption('PART');
    await dialog.getByLabel('Course').selectOption('course-1');

    await expect(dialog.getByRole('button', { name: /generate/i })).toBeDisabled();
  });

  test('sends coursePartId when generating a PART card', async ({ page, signIn }) => {
    await signIn('admin');
    const dialog = await openGenerate(page);

    await dialog.getByLabel('What do these cards unlock?').selectOption('PART');
    await dialog.getByLabel('Course').selectOption('course-1');
    await dialog.getByLabel('Part').selectOption('part-1');
    await dialog.getByLabel('How many cards').fill('10');
    // Wait for the request to land before asking the stub what it received —
    // reading straight after the click raced the browser and flaked.
    await Promise.all([
      page.waitForResponse((r) => r.url().includes('/api/proxy/admin/codes/generate')),
      dialog.getByRole('button', { name: /generate/i }).click(),
    ]);

    const sent = await (
      await page.request.get(`${STUB_API}/api/v1/__test__/last-generate-codes`)
    ).json();

    expect(sent.data.targetType).toBe('PART');
    expect(sent.data.coursePartId).toBe('part-1');
    expect(sent.data.courseId).toBe('course-1');
    expect(sent.data.count).toBe(10);
  });

  test('still generates a whole-course card the old way', async ({ page, signIn }) => {
    await signIn('admin');
    const dialog = await openGenerate(page);

    await dialog.getByLabel('Course').selectOption('course-1');
    await dialog.getByLabel('How many cards').fill('5');
    // Wait for the request to land before asking the stub what it received —
    // reading straight after the click raced the browser and flaked.
    await Promise.all([
      page.waitForResponse((r) => r.url().includes('/api/proxy/admin/codes/generate')),
      dialog.getByRole('button', { name: /generate/i }).click(),
    ]);

    const sent = await (
      await page.request.get(`${STUB_API}/api/v1/__test__/last-generate-codes`)
    ).json();

    expect(sent.data.targetType).toBe('COURSE');
    expect(sent.data.courseId).toBe('course-1');
    // The part must not leak into a target that has nothing to do with it.
    expect(sent.data.coursePartId).toBeUndefined();
  });

  test('still generates a section card', async ({ page, signIn }) => {
    await signIn('admin');
    const dialog = await openGenerate(page);

    await dialog.getByLabel('What do these cards unlock?').selectOption('SECTION');
    await dialog.getByLabel('Course').selectOption('course-1');
    await dialog.getByLabel('Section').selectOption('sec-1');
    // Wait for the request to land before asking the stub what it received —
    // reading straight after the click raced the browser and flaked.
    await Promise.all([
      page.waitForResponse((r) => r.url().includes('/api/proxy/admin/codes/generate')),
      dialog.getByRole('button', { name: /generate/i }).click(),
    ]);

    const sent = await (
      await page.request.get(`${STUB_API}/api/v1/__test__/last-generate-codes`)
    ).json();

    expect(sent.data.targetType).toBe('SECTION');
    expect(sent.data.sectionId).toBe('sec-1');
    expect(sent.data.coursePartId).toBeUndefined();
  });

  test('shows PART as a readable label rather than a raw enum', async ({ page, signIn }) => {
    await signIn('admin');
    await page.goto('/codes');

    await expect(page.getByLabel('Target type').locator('option')).toContainText([
      'Course part',
    ]);
  });

  test('code generation stays refused to a teacher', async ({ page, signIn }) => {
    // Every admin code route is @AdminOnly(); adding PART changed none of that.
    await signIn('teacher');

    const response = await page.request.post('/api/proxy/admin/codes/generate', {
      headers: { 'x-dashboard-request': '1', origin: new URL(page.url()).origin },
      data: { targetType: 'PART', courseId: 'course-1', coursePartId: 'part-1', count: 1 },
    });

    expect(response.status(), await response.text()).toBe(403);
  });
});
