import type { Metadata } from 'next';
import Link from 'next/link';

import { ContactList } from '@/features/public-site/contact-list';
import { PublicShell, Section } from '@/features/public-site/shell';
import { parseLang, type Lang } from '@/features/public-site/site';

export const metadata: Metadata = { title: 'Privacy Policy' };

/*
 * Every statement on this page was traced to the code (mobile app, API and
 * database schema) at the time of writing. If the app starts collecting
 * something new, this page has to change in the same release — and so do the
 * Google Play Data safety form and the App Store privacy answers
 * (see the release/ folder in the mobile repository).
 */

export default async function PrivacyPage({
  searchParams,
}: {
  searchParams: Promise<{ lang?: string }>;
}) {
  const lang = parseLang((await searchParams).lang);
  return (
    <PublicShell
      lang={lang}
      path="/privacy"
      title={lang === 'ar' ? 'سياسة الخصوصية' : 'Privacy Policy'}
    >
      {lang === 'ar' ? <Arabic /> : <English />}
    </PublicShell>
  );
}

function deletionLink(lang: Lang) {
  return lang === 'ar' ? '/account-deletion?lang=ar' : '/account-deletion';
}

function English() {
  return (
    <>
      <Section title="1. About this policy">
        <p>
          This policy explains what information the Student Center mobile app (Android and iOS)
          collects, why, who can see it, how long it is kept, and the choices you have. Student
          Center is a learning app for university students: it lets you follow courses, watch
          lessons, open lesson attachments and library materials, receive notifications and
          contact support.
        </p>
      </Section>

      <Section title="2. Information you give us">
        <p>When you create an account we ask for:</p>
        <ul>
          <li>your full name;</li>
          <li>your Egyptian mobile phone number, which is also your sign-in name;</li>
          <li>
            a password — we store only a one-way cryptographic hash of it, never the password
            itself;
          </li>
          <li>your gender;</li>
          <li>your university, faculty, department and academic year;</li>
          <li>your preferred language (Arabic or English).</li>
        </ul>
        <p>Optionally, you may also give us:</p>
        <ul>
          <li>
            a profile photo, which you pick yourself from your photo library (the app does not
            use the camera);
          </li>
          <li>
            the messages you write to support inside the app, including account-deletion
            requests;
          </li>
          <li>access codes and recharge-card codes you type in to unlock content or add credit.</li>
        </ul>
        <p>We do not ask students for an email address.</p>
      </Section>

      <Section title="3. Information created while you use the app">
        <ul>
          <li>
            <strong>Learning activity:</strong> the courses and course parts you join and how
            (free, access code, or administration approval); lessons you watch, your playback
            position, time watched and completion; library materials you unlock.
          </li>
          <li>
            <strong>Wallet and purchase records:</strong> codes and cards you redeem, your wallet
            credit balance and every credit or debit on it, and library purchases.
          </li>
          <li>
            <strong>Notifications:</strong> the in-app notifications sent to you, whether you have
            read them, and your notification preferences.
          </li>
        </ul>
      </Section>

      <Section title="4. Device and security information">
        <p>
          To protect course content and to limit an account to the device(s) the administration
          allows, the app sends the following with its requests:
        </p>
        <ul>
          <li>
            a device identifier generated by the app: a random secret stored in your device&apos;s
            secure storage, combined with a system identifier and hashed on the device — only the
            hash leaves the device;
          </li>
          <li>
            your device&apos;s name, model, platform (Android or iOS), operating-system version
            and app version, and whether the device appears to be an emulator or modified;
          </li>
          <li>
            the IP address and user agent of requests for sign-in, sessions and video playback;
          </li>
          <li>
            security events: successful and failed sign-ins, sign-ins from a new device, and
            screen recording, screenshots or external displays detected while a protected video
            is playing.
          </li>
        </ul>
        <p>
          Lesson videos show a visible watermark that includes your name and an account reference,
          so that recordings can be traced.
        </p>
        <p>
          If you allow notifications, the app also sends us a push-notification token so that we
          can deliver notifications to your device.
        </p>
      </Section>

      <Section title="5. What we do not collect">
        <p>
          The app does not access your location, contacts, camera or microphone, does not use an
          advertising identifier, shows no third-party advertising, contains no third-party
          analytics or crash-reporting tools, and does not track you across other apps or
          websites. The app does not collect payment-card details.
        </p>
      </Section>

      <Section title="6. How we use information">
        <ul>
          <li>to create and secure your account and keep you signed in;</li>
          <li>to decide which courses, lessons and materials you can open, and to show your progress;</li>
          <li>to protect content: device binding, watermarking and detecting screen capture;</li>
          <li>to keep wallet and purchase records accurate;</li>
          <li>to send you notifications about your courses and announcements;</li>
          <li>to answer your support requests;</li>
          <li>to prevent fraud, account sharing and abuse, and to investigate security problems;</li>
          <li>to produce course statistics for the platform administration and instructors.</li>
        </ul>
        <p>We do not sell your information and do not use it for advertising.</p>
      </Section>

      <Section title="7. Who can see your information">
        <ul>
          <li>
            <strong>Platform administrators</strong> can see your account details, enrollments,
            progress, wallet and purchase records, devices and support conversations, in order to
            run the service.
          </li>
          <li>
            <strong>Instructors</strong> manage the courses assigned to them, can send
            notifications to the students of those courses, and can see statistics about them.
          </li>
          <li>
            <strong>Service providers</strong> that host or process data for us, only to run the
            service: Render (application server), Neon (database), Upstash (cache and job
            queues), Cloudflare (file and video storage and delivery), Vercel (web pages and the
            staff dashboard), Expo (push-notification delivery and app updates), and Google
            Firebase Cloud Messaging and Apple Push Notification service (delivering
            notifications to your device).
          </li>
          <li>Authorities, when we are legally required to disclose information.</li>
        </ul>
      </Section>

      <Section title="8. Security">
        <p>
          All communication between the app and our servers uses HTTPS. Passwords are stored only
          as hashes; sign-in tokens are kept in your device&apos;s secure storage and are
          rotated; refresh tokens are stored on our side only as hashes; staff access is limited
          by role. No system is perfectly secure, and we cannot guarantee absolute security.
        </p>
      </Section>

      <Section title="9. How long we keep information">
        <p>
          We keep your information while your account exists. Expired sign-in sessions are
          deleted about 30 days after they expire.
        </p>
        <p>When your account is deleted:</p>
        <ul>
          <li>the account is disabled and can no longer sign in;</li>
          <li>you are signed out on every device and any video access is revoked;</li>
          <li>your phone number is released so it can be used to register again.</li>
        </ul>
        <p>
          We keep the records the platform needs for financial, security and audit purposes —
          enrollments, redeemed codes, wallet transactions, purchases, support conversations and
          security and audit logs — together with the disabled account record they refer to,
          which includes your name, phone number, academic details, profile photo, devices and learning progress. These records are not visible in the app
          and are used only for those purposes.
        </p>
      </Section>

      <Section title="10. Your choices">
        <ul>
          <li>You can update your profile, language and profile photo in the app.</li>
          <li>You can turn notifications off in the app or in your device settings.</li>
          <li>
            You can ask to delete your account from inside the app or on the{' '}
            <Link href={deletionLink('en')}>account deletion page</Link>.
          </li>
          <li>You can contact us to ask for a copy or correction of your information.</li>
        </ul>
      </Section>

      <Section title="11. Children">
        <p>
          Student Center is intended for university students. It is not directed to children, and
          we do not knowingly collect information from children under 13.
        </p>
      </Section>

      <Section title="12. This website">
        <p>
          These web pages do not use cookies. The hosting provider counts page views anonymously,
          and your browser remembers your light or dark theme choice locally.
        </p>
      </Section>

      <Section title="13. Changes">
        <p>
          If we change this policy we will update this page and the date at the top. Significant
          changes will also be announced in the app.
        </p>
      </Section>

      <Section title="14. Contact">
        <p>Questions about this policy or your information:</p>
        <ContactList lang="en" />
      </Section>
    </>
  );
}

function Arabic() {
  return (
    <>
      <Section title="١. عن هذه السياسة">
        <p>
          توضح هذه السياسة ما يجمعه تطبيق Student Center (أندرويد وiOS) من معلومات، ولماذا، ومن
          يمكنه الاطلاع عليها، ومدة الاحتفاظ بها، والخيارات المتاحة لك. Student Center تطبيق تعليمي
          لطلاب الجامعات يتيح لك متابعة الكورسات ومشاهدة الدروس وفتح مرفقات الدروس ومواد المكتبة
          واستقبال الإشعارات والتواصل مع الدعم.
        </p>
      </Section>

      <Section title="٢. المعلومات التي تقدمها لنا">
        <p>عند إنشاء الحساب نطلب:</p>
        <ul>
          <li>اسمك الكامل؛</li>
          <li>رقم هاتفك المحمول المصري، وهو أيضًا اسم الدخول؛</li>
          <li>كلمة مرور — نحفظ فقط بصمة مشفّرة أحادية الاتجاه لها، ولا نحفظ كلمة المرور نفسها؛</li>
          <li>النوع (ذكر/أنثى)؛</li>
          <li>الجامعة والكلية والقسم والفرقة الدراسية؛</li>
          <li>اللغة المفضلة (العربية أو الإنجليزية).</li>
        </ul>
        <p>ويمكنك اختياريًا أن تقدم:</p>
        <ul>
          <li>صورة شخصية تختارها بنفسك من مكتبة الصور (التطبيق لا يستخدم الكاميرا)؛</li>
          <li>الرسائل التي تكتبها للدعم داخل التطبيق، بما فيها طلبات حذف الحساب؛</li>
          <li>أكواد الوصول وأكواد كروت الشحن التي تُدخلها لفتح المحتوى أو إضافة رصيد.</li>
        </ul>
        <p>لا نطلب من الطلاب بريدًا إلكترونيًا.</p>
      </Section>

      <Section title="٣. معلومات تنشأ أثناء استخدامك للتطبيق">
        <ul>
          <li>
            <strong>النشاط التعليمي:</strong> الكورسات وأجزاء الكورسات التي تنضم إليها وطريقة
            الانضمام (مجاني، كود وصول، أو موافقة الإدارة)؛ الدروس التي تشاهدها وموضع التشغيل ومدة
            المشاهدة والإكمال؛ مواد المكتبة التي تفتحها.
          </li>
          <li>
            <strong>المحفظة وسجلات الشراء:</strong> الأكواد والكروت التي تستخدمها، ورصيد محفظتك وكل
            عملية إضافة أو خصم عليها، ومشتريات المكتبة.
          </li>
          <li>
            <strong>الإشعارات:</strong> الإشعارات المرسلة إليك داخل التطبيق وحالة قراءتها وتفضيلات
            الإشعارات.
          </li>
        </ul>
      </Section>

      <Section title="٤. معلومات الجهاز والأمان">
        <p>لحماية المحتوى ولربط الحساب بالجهاز أو الأجهزة التي تسمح بها الإدارة، يرسل التطبيق مع طلباته:</p>
        <ul>
          <li>
            معرّف جهاز يُنشئه التطبيق: سرّ عشوائي محفوظ في التخزين الآمن لجهازك يُدمج مع معرّف من
            النظام ثم يُشفّر على الجهاز — ولا يخرج من الجهاز إلا الناتج المشفّر؛
          </li>
          <li>
            اسم الجهاز وطرازه ونظام التشغيل (أندرويد أو iOS) وإصداره وإصدار التطبيق، وما إذا كان
            الجهاز يبدو محاكيًا أو معدّلًا؛
          </li>
          <li>عنوان IP ومعرّف المتصفح/التطبيق لطلبات تسجيل الدخول والجلسات وتشغيل الفيديو؛</li>
          <li>
            أحداث الأمان: محاولات الدخول الناجحة والفاشلة، والدخول من جهاز جديد، واكتشاف تسجيل الشاشة
            أو لقطات الشاشة أو الشاشات الخارجية أثناء تشغيل فيديو محمي.
          </li>
        </ul>
        <p>تعرض فيديوهات الدروس علامة مائية ظاهرة تتضمن اسمك ومرجعًا لحسابك حتى يمكن تتبّع أي تسجيل.</p>
        <p>إذا سمحت بالإشعارات، يرسل التطبيق رمز إشعارات (Push token) لتوصيل الإشعارات إلى جهازك.</p>
      </Section>

      <Section title="٥. ما لا نجمعه">
        <p>
          لا يصل التطبيق إلى موقعك أو جهات الاتصال أو الكاميرا أو الميكروفون، ولا يستخدم معرّف
          الإعلانات، ولا يعرض إعلانات من أطراف أخرى، ولا يحتوي على أدوات تحليلات أو تقارير أعطال من
          أطراف أخرى، ولا يتتبعك عبر تطبيقات أو مواقع أخرى. ولا يجمع التطبيق بيانات بطاقات الدفع.
        </p>
      </Section>

      <Section title="٦. كيف نستخدم المعلومات">
        <ul>
          <li>لإنشاء حسابك وتأمينه وإبقائك مسجّل الدخول؛</li>
          <li>لتحديد الكورسات والدروس والمواد المتاحة لك وعرض تقدّمك؛</li>
          <li>لحماية المحتوى: ربط الجهاز والعلامة المائية واكتشاف تسجيل الشاشة؛</li>
          <li>للحفاظ على دقة سجلات المحفظة والشراء؛</li>
          <li>لإرسال إشعارات عن كورساتك والإعلانات؛</li>
          <li>للرد على طلبات الدعم؛</li>
          <li>لمنع الاحتيال ومشاركة الحسابات وإساءة الاستخدام والتحقيق في مشكلات الأمان؛</li>
          <li>لإعداد إحصائيات الكورسات لإدارة المنصة والمحاضرين.</li>
        </ul>
        <p>لا نبيع معلوماتك ولا نستخدمها لأغراض إعلانية.</p>
      </Section>

      <Section title="٧. من يمكنه الاطلاع على معلوماتك">
        <ul>
          <li>
            <strong>إدارة المنصة:</strong> يمكنها الاطلاع على بيانات حسابك واشتراكاتك وتقدّمك وسجلات
            المحفظة والشراء والأجهزة ومحادثات الدعم لتشغيل الخدمة.
          </li>
          <li>
            <strong>المحاضرون:</strong> يديرون الكورسات المسندة إليهم، ويمكنهم إرسال إشعارات لطلاب
            هذه الكورسات والاطلاع على إحصائياتها.
          </li>
          <li>
            <strong>مزوّدو الخدمات</strong> الذين يستضيفون البيانات أو يعالجونها لصالحنا لتشغيل الخدمة
            فقط: Render (خادم التطبيق)، Neon (قاعدة البيانات)، Upstash (التخزين المؤقت وقوائم
            المهام)، Cloudflare (تخزين الملفات والفيديو وتوصيلها)، Vercel (صفحات الويب ولوحة
            الإدارة)، Expo (توصيل الإشعارات وتحديثات التطبيق)، وخدمتا Google Firebase Cloud
            Messaging وApple Push Notification لتوصيل الإشعارات إلى جهازك.
          </li>
          <li>الجهات الرسمية، عندما يُلزمنا القانون بالإفصاح.</li>
        </ul>
      </Section>

      <Section title="٨. الأمان">
        <p>
          يتم كل الاتصال بين التطبيق وخوادمنا عبر HTTPS. تُحفظ كلمات المرور كبصمات مشفّرة فقط، وتُحفظ
          رموز الدخول في التخزين الآمن لجهازك ويتم تجديدها، ولا نحفظ رموز التجديد لدينا إلا مشفّرة،
          وصلاحيات فريق العمل محددة حسب الدور. لا يوجد نظام آمن تمامًا، ولا يمكننا ضمان الأمان المطلق.
        </p>
      </Section>

      <Section title="٩. مدة الاحتفاظ بالمعلومات">
        <p>نحتفظ بمعلوماتك طالما حسابك موجود. تُحذف جلسات الدخول المنتهية بعد نحو ٣٠ يومًا من انتهائها.</p>
        <p>عند حذف حسابك:</p>
        <ul>
          <li>يتم تعطيل الحساب ولا يمكن الدخول به؛</li>
          <li>يتم تسجيل خروجك من كل الأجهزة وإلغاء أي صلاحية لتشغيل الفيديو؛</li>
          <li>يتم تحرير رقم هاتفك ليمكن التسجيل به من جديد.</li>
        </ul>
        <p>
          نحتفظ بالسجلات التي تحتاجها المنصة لأغراض مالية وأمنية ورقابية — الاشتراكات والأكواد
          المستخدمة ومعاملات المحفظة والمشتريات ومحادثات الدعم وسجلات الأمان والتدقيق — مع سجل الحساب
          المعطّل الذي تشير إليه، والذي يتضمن اسمك ورقم هاتفك وبياناتك الدراسية وصورتك الشخصية وأجهزتك وتقدّمك في الدروس. لا تظهر هذه السجلات في التطبيق ولا
          تُستخدم إلا لهذه الأغراض.
        </p>
      </Section>

      <Section title="١٠. خياراتك">
        <ul>
          <li>يمكنك تعديل ملفك الشخصي واللغة والصورة الشخصية من التطبيق.</li>
          <li>يمكنك إيقاف الإشعارات من التطبيق أو من إعدادات جهازك.</li>
          <li>
            يمكنك طلب حذف حسابك من داخل التطبيق أو من{' '}
            <Link href={deletionLink('ar')}>صفحة حذف الحساب</Link>.
          </li>
          <li>يمكنك التواصل معنا لطلب نسخة من معلوماتك أو تصحيحها.</li>
        </ul>
      </Section>

      <Section title="١١. الأطفال">
        <p>
          Student Center موجّه لطلاب الجامعات، وليس موجّهًا للأطفال، ولا نجمع عن علم معلومات من
          أطفال دون ١٣ عامًا.
        </p>
      </Section>

      <Section title="١٢. هذا الموقع">
        <p>
          لا تستخدم صفحات الويب هذه ملفات تعريف الارتباط (Cookies). يحسب مزوّد الاستضافة عدد
          الزيارات دون تحديد هوية الزائر، ويحفظ متصفحك اختيارك للوضع الفاتح أو الداكن محليًا.
        </p>
      </Section>

      <Section title="١٣. التغييرات">
        <p>
          إذا غيّرنا هذه السياسة سنحدّث هذه الصفحة والتاريخ أعلاها، وسنعلن التغييرات المهمة داخل
          التطبيق أيضًا.
        </p>
      </Section>

      <Section title="١٤. التواصل">
        <p>للاستفسار عن هذه السياسة أو عن معلوماتك:</p>
        <ContactList lang="ar" />
      </Section>
    </>
  );
}
